### ISSUE TITLE
Error: Stock Is Forbidden

### ISSUE THREAD

**Issue by aysark** [Wei-Xia/alfred-stock-price-workflow#5]
Cool workflow.  When i try to search a ticker, i get this error:

```
Stock Is Forbidden
```

-
Stock 1.0
Alfred 4.3
darwin x64 19.6.0

---

I thought it'd be due to app Security but don't see anything there.

**Comment by cellulosa** [comment]
hi @aysark I had your same issue and then I realised the `copy to clipboard` IEX button adds a space. Just make sure to remove it when you paste the variable onto the Alfred preference.

Also make sure you are coping the public key.

**Comment by Wei-Xia** [comment]
@aysark  please make sure you're using correct API key....and test it with IEX API call before filling it in the plugin.

**Comment by Wei-Xia** [comment]
close it as it's not an issue.
