### ISSUE TITLE
Suggestion: Accept ISIN as alternative input

### ISSUE THREAD

**Issue by chrisgrieser** [Wei-Xia/alfred-stock-price-workflow#8]
It seems only the Symbol is accepted as input (e.g. `AAPL`), however I more often than not work with the ISIN instead (e.g. `US0378331005`), which is also internationally the more common standard. Therefore, I would suggest accepting ISIN as alternative input.

**Comment by Wei-Xia** [comment]
Hi @chrisgrieser  Thanks for the suggestion!

This workflow is using [IEX Cloud API](https://iexcloud.io/) to get the real-time stock price for displaying.....

After checking their API document, I find out that they only support [ISIN Mapping](https://iexcloud.io/docs/api/#isin-mapping), which couldn't retrieve real-time stock price.

So it might be difficult to find the workaround to accomplish this feature improvement.

**Comment by chrisgrieser** [comment]
Too bad.

A ISIN-Symbol-Converter would also be quite useful, but thats probably a different workflow. (Stock-related Workflows are really a rarity on Alfred).

**Comment by Wei-Xia** [comment]
that's true....stock related workflows are rare in Alfred.
